set_property PACKAGE_PIN R16 [get_ports hsync_i_0]
set_property PACKAGE_PIN R17 [get_ports vsync_i_0]
set_property PACKAGE_PIN T17 [get_ports vsync_o_0]
set_property PACKAGE_PIN R18 [get_ports hsync_o_0]
set_property IOSTANDARD LVCMOS33 [get_ports hsync_i_0]
set_property IOSTANDARD LVCMOS33 [get_ports hsync_o_0]
set_property IOSTANDARD LVCMOS33 [get_ports vsync_i_0]
set_property IOSTANDARD LVCMOS33 [get_ports vsync_o_0]
set_property PACKAGE_PIN Y14 [get_ports {rgb_i_0[15]}]
set_property PACKAGE_PIN W14 [get_ports {rgb_i_0[14]}]
set_property PACKAGE_PIN Y17 [get_ports {rgb_i_0[13]}]
set_property PACKAGE_PIN Y16 [get_ports {rgb_i_0[12]}]
set_property PACKAGE_PIN R14 [get_ports {rgb_i_0[11]}]
set_property PACKAGE_PIN P14 [get_ports {rgb_i_0[10]}]
set_property PACKAGE_PIN T15 [get_ports {rgb_i_0[9]}]
set_property PACKAGE_PIN T14 [get_ports {rgb_i_0[8]}]
set_property PACKAGE_PIN W13 [get_ports {rgb_i_0[7]}]
set_property PACKAGE_PIN V12 [get_ports {rgb_i_0[6]}]
set_property PACKAGE_PIN V13 [get_ports {rgb_i_0[5]}]
set_property PACKAGE_PIN R19 [get_ports {rgb_i_0[4]}]
set_property PACKAGE_PIN U12 [get_ports {rgb_i_0[3]}]
set_property PACKAGE_PIN T12 [get_ports {rgb_i_0[2]}]
set_property PACKAGE_PIN T10 [get_ports {rgb_i_0[1]}]
set_property PACKAGE_PIN T11 [get_ports {rgb_i_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[0]}]
set_property PACKAGE_PIN W16 [get_ports {rgb_o_0[15]}]
set_property PACKAGE_PIN V16 [get_ports {rgb_o_0[14]}]
set_property PACKAGE_PIN Y19 [get_ports {rgb_o_0[13]}]
set_property PACKAGE_PIN Y18 [get_ports {rgb_o_0[12]}]
set_property PACKAGE_PIN W20 [get_ports {rgb_o_0[11]}]
set_property PACKAGE_PIN V20 [get_ports {rgb_o_0[10]}]
set_property PACKAGE_PIN U20 [get_ports {rgb_o_0[9]}]
set_property PACKAGE_PIN T20 [get_ports {rgb_o_0[8]}]
set_property PACKAGE_PIN U19 [get_ports {rgb_o_0[7]}]
set_property PACKAGE_PIN U18 [get_ports {rgb_o_0[6]}]
set_property PACKAGE_PIN U15 [get_ports {rgb_o_0[5]}]
set_property PACKAGE_PIN U14 [get_ports {rgb_o_0[4]}]
set_property PACKAGE_PIN W15 [get_ports {rgb_o_0[3]}]
set_property PACKAGE_PIN V15 [get_ports {rgb_o_0[2]}]
set_property PACKAGE_PIN U17 [get_ports {rgb_o_0[1]}]
set_property PACKAGE_PIN T16 [get_ports {rgb_o_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[0]}]

#set_clock_groups -name in_axi -asynchronous -group [get_clocks clk_fpga_1]
#set_clock_groups -name out_frame -asynchronous -group [get_clocks clk_fpga_0]

set_false_path -from [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_0]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_1]

set_property PACKAGE_PIN W18 [get_ports adc_clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports adc_clk_0]

create_clock -period 16666667.000 -name vsync_i_0 [get_ports vsync_i_0]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list zynq_i/processing_system7_0/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {zynq_i/transactor_0/wdata[0]} {zynq_i/transactor_0/wdata[1]} {zynq_i/transactor_0/wdata[2]} {zynq_i/transactor_0/wdata[3]} {zynq_i/transactor_0/wdata[4]} {zynq_i/transactor_0/wdata[5]} {zynq_i/transactor_0/wdata[6]} {zynq_i/transactor_0/wdata[7]} {zynq_i/transactor_0/wdata[8]} {zynq_i/transactor_0/wdata[9]} {zynq_i/transactor_0/wdata[10]} {zynq_i/transactor_0/wdata[11]} {zynq_i/transactor_0/wdata[12]} {zynq_i/transactor_0/wdata[13]} {zynq_i/transactor_0/wdata[14]} {zynq_i/transactor_0/wdata[15]} {zynq_i/transactor_0/wdata[16]} {zynq_i/transactor_0/wdata[17]} {zynq_i/transactor_0/wdata[18]} {zynq_i/transactor_0/wdata[19]} {zynq_i/transactor_0/wdata[20]} {zynq_i/transactor_0/wdata[21]} {zynq_i/transactor_0/wdata[22]} {zynq_i/transactor_0/wdata[23]} {zynq_i/transactor_0/wdata[24]} {zynq_i/transactor_0/wdata[25]} {zynq_i/transactor_0/wdata[26]} {zynq_i/transactor_0/wdata[27]} {zynq_i/transactor_0/wdata[28]} {zynq_i/transactor_0/wdata[29]} {zynq_i/transactor_0/wdata[30]} {zynq_i/transactor_0/wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {zynq_i/transactor_0/rdata[0]} {zynq_i/transactor_0/rdata[1]} {zynq_i/transactor_0/rdata[2]} {zynq_i/transactor_0/rdata[3]} {zynq_i/transactor_0/rdata[4]} {zynq_i/transactor_0/rdata[5]} {zynq_i/transactor_0/rdata[6]} {zynq_i/transactor_0/rdata[7]} {zynq_i/transactor_0/rdata[8]} {zynq_i/transactor_0/rdata[9]} {zynq_i/transactor_0/rdata[10]} {zynq_i/transactor_0/rdata[11]} {zynq_i/transactor_0/rdata[12]} {zynq_i/transactor_0/rdata[13]} {zynq_i/transactor_0/rdata[14]} {zynq_i/transactor_0/rdata[15]} {zynq_i/transactor_0/rdata[16]} {zynq_i/transactor_0/rdata[17]} {zynq_i/transactor_0/rdata[18]} {zynq_i/transactor_0/rdata[19]} {zynq_i/transactor_0/rdata[20]} {zynq_i/transactor_0/rdata[21]} {zynq_i/transactor_0/rdata[22]} {zynq_i/transactor_0/rdata[23]} {zynq_i/transactor_0/rdata[24]} {zynq_i/transactor_0/rdata[25]} {zynq_i/transactor_0/rdata[26]} {zynq_i/transactor_0/rdata[27]} {zynq_i/transactor_0/rdata[28]} {zynq_i/transactor_0/rdata[29]} {zynq_i/transactor_0/rdata[30]} {zynq_i/transactor_0/rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 14 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {zynq_i/transactor_0/awaddr[8]} {zynq_i/transactor_0/awaddr[9]} {zynq_i/transactor_0/awaddr[10]} {zynq_i/transactor_0/awaddr[11]} {zynq_i/transactor_0/awaddr[12]} {zynq_i/transactor_0/awaddr[13]} {zynq_i/transactor_0/awaddr[14]} {zynq_i/transactor_0/awaddr[15]} {zynq_i/transactor_0/awaddr[16]} {zynq_i/transactor_0/awaddr[17]} {zynq_i/transactor_0/awaddr[18]} {zynq_i/transactor_0/awaddr[19]} {zynq_i/transactor_0/awaddr[26]} {zynq_i/transactor_0/awaddr[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 14 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {zynq_i/transactor_0/araddr[8]} {zynq_i/transactor_0/araddr[9]} {zynq_i/transactor_0/araddr[10]} {zynq_i/transactor_0/araddr[11]} {zynq_i/transactor_0/araddr[12]} {zynq_i/transactor_0/araddr[13]} {zynq_i/transactor_0/araddr[14]} {zynq_i/transactor_0/araddr[15]} {zynq_i/transactor_0/araddr[16]} {zynq_i/transactor_0/araddr[17]} {zynq_i/transactor_0/araddr[18]} {zynq_i/transactor_0/araddr[19]} {zynq_i/transactor_0/araddr[26]} {zynq_i/transactor_0/araddr[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {zynq_i/transactor_0/rgb_o[0]} {zynq_i/transactor_0/rgb_o[1]} {zynq_i/transactor_0/rgb_o[2]} {zynq_i/transactor_0/rgb_o[3]} {zynq_i/transactor_0/rgb_o[4]} {zynq_i/transactor_0/rgb_o[5]} {zynq_i/transactor_0/rgb_o[6]} {zynq_i/transactor_0/rgb_o[7]} {zynq_i/transactor_0/rgb_o[8]} {zynq_i/transactor_0/rgb_o[9]} {zynq_i/transactor_0/rgb_o[10]} {zynq_i/transactor_0/rgb_o[11]} {zynq_i/transactor_0/rgb_o[12]} {zynq_i/transactor_0/rgb_o[13]} {zynq_i/transactor_0/rgb_o[14]} {zynq_i/transactor_0/rgb_o[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {zynq_i/transactor_0/rgb_i[0]} {zynq_i/transactor_0/rgb_i[1]} {zynq_i/transactor_0/rgb_i[2]} {zynq_i/transactor_0/rgb_i[3]} {zynq_i/transactor_0/rgb_i[4]} {zynq_i/transactor_0/rgb_i[5]} {zynq_i/transactor_0/rgb_i[6]} {zynq_i/transactor_0/rgb_i[7]} {zynq_i/transactor_0/rgb_i[8]} {zynq_i/transactor_0/rgb_i[9]} {zynq_i/transactor_0/rgb_i[10]} {zynq_i/transactor_0/rgb_i[11]} {zynq_i/transactor_0/rgb_i[12]} {zynq_i/transactor_0/rgb_i[13]} {zynq_i/transactor_0/rgb_i[14]} {zynq_i/transactor_0/rgb_i[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {zynq_i/S00_AXI_1_BRESP[0]} {zynq_i/S00_AXI_1_BRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list zynq_i/adc_clk_0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list zynq_i/transactor_0/arready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list zynq_i/transactor_0/arvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list zynq_i/transactor_0/awready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list zynq_i/transactor_0/awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list zynq_i/transactor_0/clk25]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list zynq_i/transactor_0/hsync_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list zynq_i/transactor_0/hsync_o]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list zynq_i/transactor_0/resetn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list zynq_i/transactor_0/rlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list zynq_i/transactor_0/rready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list zynq_i/transactor_0/rvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list zynq_i/transactor_0/vsync_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list zynq_i/transactor_0/wready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list zynq_i/transactor_0/wvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list zynq_i/S00_AXI_1_BREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list zynq_i/S00_AXI_1_BVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets adc_clk_0_OBUF]
