set_property PACKAGE_PIN R16 [get_ports hsync_i_0]
set_property PACKAGE_PIN R17 [get_ports vsync_i_0]
set_property PACKAGE_PIN T17 [get_ports vsync_o_0]
set_property PACKAGE_PIN R18 [get_ports hsync_o_0]
set_property IOSTANDARD LVCMOS33 [get_ports hsync_i_0]
set_property IOSTANDARD LVCMOS33 [get_ports hsync_o_0]
set_property IOSTANDARD LVCMOS33 [get_ports vsync_i_0]
set_property IOSTANDARD LVCMOS33 [get_ports vsync_o_0]
set_property PACKAGE_PIN Y14 [get_ports {rgb_i_0[15]}]
set_property PACKAGE_PIN W14 [get_ports {rgb_i_0[14]}]
set_property PACKAGE_PIN Y17 [get_ports {rgb_i_0[13]}]
set_property PACKAGE_PIN Y16 [get_ports {rgb_i_0[12]}]
set_property PACKAGE_PIN R14 [get_ports {rgb_i_0[11]}]
set_property PACKAGE_PIN P14 [get_ports {rgb_i_0[10]}]
set_property PACKAGE_PIN T15 [get_ports {rgb_i_0[9]}]
set_property PACKAGE_PIN T14 [get_ports {rgb_i_0[8]}]
set_property PACKAGE_PIN W13 [get_ports {rgb_i_0[7]}]
set_property PACKAGE_PIN V12 [get_ports {rgb_i_0[6]}]
set_property PACKAGE_PIN V13 [get_ports {rgb_i_0[5]}]
set_property PACKAGE_PIN R19 [get_ports {rgb_i_0[4]}]
set_property PACKAGE_PIN U12 [get_ports {rgb_i_0[3]}]
set_property PACKAGE_PIN T12 [get_ports {rgb_i_0[2]}]
set_property PACKAGE_PIN T10 [get_ports {rgb_i_0[1]}]
set_property PACKAGE_PIN T11 [get_ports {rgb_i_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_i_0[0]}]
set_property PACKAGE_PIN W16 [get_ports {rgb_o_0[15]}]
set_property PACKAGE_PIN V16 [get_ports {rgb_o_0[14]}]
set_property PACKAGE_PIN Y19 [get_ports {rgb_o_0[13]}]
set_property PACKAGE_PIN Y18 [get_ports {rgb_o_0[12]}]
set_property PACKAGE_PIN W20 [get_ports {rgb_o_0[11]}]
set_property PACKAGE_PIN V20 [get_ports {rgb_o_0[10]}]
set_property PACKAGE_PIN U20 [get_ports {rgb_o_0[9]}]
set_property PACKAGE_PIN T20 [get_ports {rgb_o_0[8]}]
set_property PACKAGE_PIN U19 [get_ports {rgb_o_0[7]}]
set_property PACKAGE_PIN U18 [get_ports {rgb_o_0[6]}]
set_property PACKAGE_PIN U15 [get_ports {rgb_o_0[5]}]
set_property PACKAGE_PIN U14 [get_ports {rgb_o_0[4]}]
set_property PACKAGE_PIN W15 [get_ports {rgb_o_0[3]}]
set_property PACKAGE_PIN V15 [get_ports {rgb_o_0[2]}]
set_property PACKAGE_PIN U17 [get_ports {rgb_o_0[1]}]
set_property PACKAGE_PIN T16 [get_ports {rgb_o_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_o_0[0]}]

#set_clock_groups -name in_axi -asynchronous -group [get_clocks clk_fpga_1]
#set_clock_groups -name out_frame -asynchronous -group [get_clocks clk_fpga_0]

set_false_path -from [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_0]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_1]

set_property PACKAGE_PIN W18 [get_ports adc_clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports adc_clk_0]

create_clock -period 16666667.000 -name vsync_i_0 [get_ports vsync_i_0]
